### ISSUE TITLE
Feature request : support of Sveltekit 2 [PR included]

### ISSUE THREAD

**Issue by MarArMar** [ntsd/sveltekit-html-minifier#3]
I upgraded Sveltekit to v2,

Which makes this warning at install time :
```
├─┬ sveltekit-html-minifier 1.0.2
│ └── ✕ unmet peer @sveltejs/kit@^1.5.0: found 2.5.0
```
I will report if I see the plugin breaking, this might simply have no impact on functionality

Thank you so much btw, I find the lib super useful ! 💛

**Comment by MarArMar** [comment]
Update : I did some tests, dev and build works fine

Trying with a deployment now

Otherwise PR will be here: 

https://github.com/ntsd/sveltekit-html-minifier/pull/4

**Comment by MarArMar** [comment]
I could deploy my website so everything seems to work fine with Sveltekit V2, at least for me 😊

**Comment by ntsd** [comment]
Thank you, already merged and published.

**Comment by MarArMar** [comment]
Superb, thanks so much

Will test today 👍

**Comment by MarArMar** [comment]
Tested, it worked with the update, thanks 👌

**Comment by ntsd** [comment]
> Tested, it worked with the update, thanks 👌

Nice, thank you for the update.
